site_name: DataBot Documentation
site_url: https://databot.intellimenta.com
copyright: Copyright &copy; 2025 Intellimenta Analytics Inc.

nav:
  - Home: index.md
  - Admin Guide:
      - Getting Started: admin_guide/getting_started.md
      - Integration with BI Tools: admin_guide/bi_integration.md
      - Production Deployment: admin_guide/production_deployment.md
      - Admin Panel Overview: admin_guide/admin_panel_overview.md
      - Embedding: admin_guide/embedding.md
      - Misc.: admin_guide/misc.md
  - Other Resources:
      - Billing: other_resources/billing.md

extra_css:
  - assets/extra.css

extra:
  CNAME: "databot.intellimenta.com"
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@IntellimentaAnalytics
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/intellimenta
    - icon: fontawesome/brands/github
      link: https://github.com/intellimenta/databot

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - navigation.expand
    - navigation.footer

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true